### ISSUE TITLE
TopicOrServiceNameDoesNotExistError due to empty topic when client is disconnecting

### ISSUE THREAD

**Issue by JimWest** [Unity-Technologies/ROS-TCP-Endpoint#56]
I'm using the tcp-endpoint version 0.2.0 and Unity 2019.4.23f1, if I'm hosting a Server (on WSL), connect with Unity3D with it and then stop the Unity3D  Connection, it seems like Unity is sending an empty message to the ros-tcp-endpoint, which raises an exception on the server side, exception is:

```
Exception in thread Thread-295:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/pattke/code/install/ros_tcp_endpoint/lib/python3/dist-packages/ros_tcp_endpoint/client.py", line 172, in run
    raise TopicOrServiceNameDoesNotExistError(error_msg)
ros_tcp_endpoint.exceptions.TopicOrServiceNameDoesNotExistError: Topic/service destination '' is not defined! Known topics are: dict_keys(['pos_srv', 'pos_rot', 'color', 'camera']) 
```

This happens multiple times after a client is disconnected. This msg should be ignored and should not throw an Exception.

**Comment by JimWest** [comment]
fixed for me in 0.3.0
